dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
xrdb -merge ~/.Xresources&
redshift -l 36.1:-86.8 -t 6500K:2200K&
nextcloud&
pasystray&


##TRACKPOINTSETTINGS
#for the vector, the last number decides how fast the velocity is. the higher the number the slower it will be
xinput set-prop 'TPPS/2 IBM TrackPoint' 'Coordinate Transformation Matrix' 1, 0, 0, 0, 1, 0, 0, 0, 15

#this can be a value between -1 and +1. higher is more accelleration. 
xinput set-prop 'TPPS/2 IBM TrackPoint'  'libinput Accel Speed' .2

protonmail-bridge &
amixer set Capture nocap &
exec i3 
