dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources
redshift&
#/home/pan/git/dwm_bar_conf/bar.sh &
#exec dwm

#slowdown trackpoing, last number, higher is slower
xinput set-prop 'TPPS/2 IBM TrackPoint' 'Coordinate Transformation Matrix' 1, 0, 0, 0, 1, 0, 0, 0, 8 &
xinput set-prop 'TPPS/2 IBM TrackPoint'  'libinput Accel Speed' .2 &

protonmail-bridge &
exec i3

